[workspace]
channels = ["conda-forge"]
name = "llmchat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
langchain = "*"
litellm = "*"
python = "3.12.*"
rich = "*"
fire = "*"

[pypi-dependencies]
langchain_huggingface = "*"
langchain_litellm = "*"
langchain-neo4j = "*"
langchain_openai = "*"
neo4j = "*"
hf_xet = "*"
gradio = "*"
